---
- hosts: internet
  tasks:
   - name: Configure switch to act as campus/internet
     nclu:
       commands:

         - add loopback lo ip address 192.168.100.1/32
         - add vlan 10 ip address 192.168.200.1/24
         - add vlan 20 ip address 192.168.201.1/24
         - add vlan 30 ip address 192.168.202.1/24
         - add vlan 40 ip address 192.168.203.1/24
         - add interface swp1 ip address 172.17.0.2/30
         - add interface swp2 ip address 172.17.0.6/30
         - add ospf router-id 192.168.100.1
         - add ospf network 172.17.0.0/30 area 0.0.0.0
         - add ospf network 172.17.0.4/30 area 0.0.0.0
         - add ospf network 192.168.200.0/21 area 0.0.0.0
         - add routing route 10.19.241.0/24 172.17.0.1 100
         - add routing route 10.19.241.0/24 172.17.0.5 100

       commit: true

- hosts: cisco9500-01
  tasks:
   - name: Configure cisco9500-01 to connect to POC network
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.1/32
         - add bgp autonomous-system 65001
         - add interface swp1 ip address 172.16.0.1/31
         - add interface swp2 ip address 172.16.0.5/31
         - add interface swp3 ip address 172.16.0.8/31
         - add interface swp4 ip address 172.17.0.1/30
         - add bgp neighbor 172.16.0.0 remote-as 65201
         - add bgp neighbor 172.16.0.4 remote-as 65202
         - add bgp neighbor 172.16.0.9 remote-as 65001
         - add bgp network 10.19.241.1/32
         - add bgp network 172.16.0.0/31
         - add bgp network 172.16.0.4/31
         - add bgp network 172.16.0.8/31
         - add ospf router-id 10.19.241.1
         - add ospf network 172.17.0.0/30 area 0.0.0.0
         - add bgp redistribute ospf metric 100

       commit: true

- hosts: cisco9500-02
  tasks:
   - name: Configure cisco9500-02 to connect to POC network
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.2/32
         - add bgp autonomous-system 65001
         - add interface swp1 ip address 172.16.0.3/31
         - add interface swp2 ip address 172.16.0.7/31
         - add interface swp3 ip address 172.16.0.9/31
         - add interface swp4 ip address 172.17.0.5/30
         - add bgp neighbor 172.16.0.2 remote-as 65201
         - add bgp neighbor 172.16.0.6 remote-as 65202
         - add bgp neighbor 172.16.0.8 remote-as 65001
         - add bgp network 10.19.241.2/32
         - add bgp network 172.16.0.2/31
         - add bgp network 172.16.0.6/31
         - add bgp network 172.16.0.8/31
         - add ospf router-id 10.19.241.2
         - add ospf network 172.17.0.4/30 area 0.0.0.0
         - add bgp redistribute ospf metric 200

       commit: true


- hosts: s1
  tasks:
   - name: Configure spine01
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.10/32
         - add bgp autonomous-system 65100
         - add bgp network 10.19.241.10/32
         - add bgp neighbor LEAFS peer-group
         - add bgp neighbor LEAFS remote-as external
         - add bgp neighbor LEAFS capability extended-nexthop
         - add bgp neighbor LEAFS description Internal Fabric Network
         - add bgp neighbor swp1-4 interface peer-group LEAFS
         - add bgp bestpath as-path multipath-relax

       commit: true

- hosts: s2
  tasks:
   - name: Configure spine02
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.11/32
         - add bgp autonomous-system 65100
         - add bgp network 10.19.241.11/32
         - add bgp neighbor LEAFS peer-group
         - add bgp neighbor LEAFS remote-as external
         - add bgp neighbor LEAFS capability extended-nexthop
         - add bgp neighbor LEAFS description Internal Fabric Network
         - add bgp neighbor swp1-4 interface peer-group LEAFS
         - add bgp bestpath as-path multipath-relax

       commit: true

- hosts: bl1
  tasks:
   - name: Configure border leaf01
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.12/32
         - add bgp autonomous-system 65201
         - add routing prefix-list ipv4 list1 seq 10 permit 10.19.241.0/24 ge 32
         - add routing prefix-list ipv4 list1 seq 20 permit 192.168.0.0/16 ge 24
         - add routing prefix-list ipv4 list1 seq 30 deny any
         - add interface swp51 ip address 172.16.0.0/31
         - add interface swp52 ip address 172.16.0.2/31
         - add bgp network 10.19.241.12/32
         - add bgp network 172.16.0.0/31
         - add bgp network 172.16.0.2/31
         - add bgp neighbor 172.16.0.1 remote-as 65001
         - add bgp neighbor 172.16.0.3 remote-as 65001
         - add bgp neighbor SPINES peer-group
         - add bgp neighbor SPINES remote-as external
         - add bgp neighbor SPINES capability extended-nexthop
         - add bgp neighbor SPINES description Internal Fabric Network
         - add bgp neighbor swp53-54 interface peer-group SPINES
         - add bgp ipv4 unicast neighbor SPINES prefix-list list1 out
         - add bgp bestpath as-path multipath-relax

       commit: true

- hosts: bl2
  tasks:
   - name: Configure border leaf02
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.13/32
         - add bgp autonomous-system 65202
         - add routing prefix-list ipv4 list1 seq 10 permit 10.19.241.0/24 ge 32
         - add routing prefix-list ipv4 list1 seq 20 permit 192.168.0.0/16 ge 24
         - add routing prefix-list ipv4 list1 seq 30 deny any
         - add interface swp47 ip address 172.16.0.4/31
         - add interface swp48 ip address 172.16.0.6/31
         - add bgp network 10.19.241.13/32
         - add bgp network 172.16.0.4/31
         - add bgp network 172.16.0.6/31
         - add bgp neighbor 172.16.0.5 remote-as 65001
         - add bgp neighbor 172.16.0.7 remote-as 65001
         - add bgp neighbor SPINES peer-group
         - add bgp neighbor SPINES remote-as external
         - add bgp neighbor SPINES capability extended-nexthop
         - add bgp neighbor SPINES description Internal Fabric Network
         - add bgp neighbor swp50 interface peer-group SPINES
         - add bgp neighbor swp52 interface peer-group SPINES
         - add bgp ipv4 unicast neighbor SPINES prefix-list list1 out
         - add bgp bestpath as-path multipath-relax

       commit: true

- hosts: l3
  tasks:
   - name: Configure leaf03
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.14/32
         - add bgp autonomous-system 65203
         - add bgp network 10.19.241.14/32
         - add bgp neighbor SPINES peer-group
         - add bgp neighbor SPINES remote-as external
         - add bgp neighbor SPINES capability extended-nexthop
         - add bgp neighbor SPINES description Internal Fabric Network
         - add bgp neighbor swp50 interface peer-group SPINES
         - add bgp neighbor swp52 interface peer-group SPINES
         - add bgp bestpath as-path multipath-relax
         - add interface swp1,swp47,swp48
         - add vlan 100
         - add bond peerlink bond slaves swp47,swp48
         - add interface peerlink.4094 clag peer-ip linklocal
         - add interface peerlink.4094 clag backup-ip 192.168.200.9 vrf mgmt
         - add interface peerlink.4094 clag sys-mac 44:38:39:FF:01:56
         - add interface peerlink.4094 clag priority 100
         - add bridge bridge ports peerlink
         - add bridge stp treeprio 8192
         - add interface swp1 post-up ip link set swp1 promisc on
         - add interface swp47 post-up ip link set swp48 promisc on
         - add interface swp48 post-up ip link set swp48 promisc on
         - add bond bond01 bond slaves swp1
         - add bond bond01 clag id 1
         - add bond bond01 bridge access 100

       commit: true

- hosts: l4
  tasks:
   - name: Configure leaf04
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.15/32
         - add bgp autonomous-system 65204
         - add bgp network 10.19.241.15/32
         - add bgp neighbor SPINES peer-group
         - add bgp neighbor SPINES remote-as external
         - add bgp neighbor SPINES capability extended-nexthop
         - add bgp neighbor SPINES description Internal Fabric Network
         - add bgp neighbor swp50 interface peer-group SPINES
         - add bgp neighbor swp52 interface peer-group SPINES
         - add bgp bestpath as-path multipath-relax
         - add interface swp1,swp47,swp48
         - add vlan 100
         - add bond peerlink bond slaves swp47,swp48
         - add interface peerlink.4094 clag peer-ip linklocal
         - add interface peerlink.4094 clag backup-ip 192.168.200.8 vrf mgmt
         - add interface peerlink.4094 clag sys-mac 44:38:39:FF:01:56
         - add bridge bridge ports peerlink
         - add bridge stp treeprio 8192
         - add interface swp1 post-up ip link set swp1 promisc on
         - add interface swp47 post-up ip link set swp47 promisc on
         - add interface swp47 post-up ip link set swp48 promisc on
         - add bond bond01 bond slaves swp1
         - add bond bond01 clag id 1
         - add bond bond01 bridge access 100

       commit: true

- name: Configure Server LACP Interfaces
  hosts: server01
  become: yes
  gather_facts: yes
  tasks:

  - name: Copy Server LACP Interface Config
    copy:
      src: configurations/{{ansible_hostname}}/interfaces
      dest: /etc/network/interfaces
    register: reboot

  - name: reboot
    reboot:
      pre_reboot_delay: 60
