---
- hosts: internet
  tasks:
   - name: Configure switch to act as campus/internet
     nclu:
       commands:

         - add loopback lo ip address 192.168.100.1/32
         - add vlan 10 ip address 192.168.200.1/24
         - add vlan 20 ip address 192.168.201.1/24
         - add vlan 30 ip address 192.168.202.1/24
         - add vlan 40 ip address 192.168.203.1/24
         - add interface swp1 ip address 172.17.0.2/30
         - add interface swp2 ip address 172.17.0.6/30
         - add ospf router-id 192.168.100.1
         - add ospf network 172.17.0.0/30 area 0.0.0.0
         - add ospf network 172.17.0.4/30 area 0.0.0.0
         - add ospf network 192.168.200.0/21 area 0.0.0.0
         - add routing route 10.19.241.0/24 172.17.0.1 100
         - add routing route 10.19.241.0/24 172.17.0.5 100

       commit: true

- hosts: cisco9500-01
  tasks:
   - name: Configure cisco9500-01 to connect to POC network
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.1/32
         - add bgp autonomous-system 65001
         - add interface swp1 ip address 172.16.0.1/31
         - add interface swp3 ip address 172.16.0.4/31
         - add interface swp4 ip address 172.17.0.1/30
         - add bgp neighbor 172.16.0.0 remote-as 65201
         - add bgp neighbor 172.16.0.5 remote-as 65001
         - add bgp network 10.19.241.1/32
         - add bgp network 172.16.0.0/31
         - add bgp network 172.16.0.4/31
         - add ospf router-id 10.19.241.1
         - add ospf network 172.17.0.0/30 area 0.0.0.0
         - add bgp redistribute ospf metric 100

       commit: true

- hosts: cisco9500-02
  tasks:
   - name: Configure cisco9500-02 to connect to POC network
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.2/32
         - add bgp autonomous-system 65001
         - add interface swp1 ip address 172.16.0.3/31
         - add interface swp3 ip address 172.16.0.5/31
         - add interface swp4 ip address 172.17.0.5/30
         - add bgp neighbor 172.16.0.2 remote-as 65201
         - add bgp neighbor 172.16.0.6 remote-as 65202
         - add bgp network 10.19.241.2/32
         - add bgp network 172.16.0.2/31
         - add bgp network 172.16.0.4/31
         - add ospf router-id 10.19.241.2
         - add ospf network 172.17.0.4/30 area 0.0.0.0
         - add bgp redistribute ospf metric 200

       commit: true


- hosts: s1
  tasks:
   - name: Configure spine01
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.10/32
         - add bgp autonomous-system 65100
         - add bgp network 10.19.241.10/32
         - add bgp neighbor LEAFS peer-group
         - add bgp neighbor LEAFS remote-as external
         - add bgp neighbor LEAFS capability extended-nexthop
         - add bgp neighbor LEAFS description Internal Fabric Network
         - add bgp neighbor swp1-4 interface peer-group LEAFS
         - add bgp bestpath as-path multipath-relax

       commit: true

- hosts: s2
  tasks:
   - name: Configure spine02
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.11/32
         - add bgp autonomous-system 65100
         - add bgp network 10.19.241.11/32
         - add bgp neighbor LEAFS peer-group
         - add bgp neighbor LEAFS remote-as external
         - add bgp neighbor LEAFS capability extended-nexthop
         - add bgp neighbor LEAFS description Internal Fabric Network
         - add bgp neighbor swp1-4 interface peer-group LEAFS
         - add bgp bestpath as-path multipath-relax

       commit: true

- hosts: bl1
  tasks:
   - name: Configure border leaf01
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.12/32
         - add bgp autonomous-system 65201
         - add routing prefix-list ipv4 list1 seq 10 permit 10.19.241.0/24 ge 32
         - add routing prefix-list ipv4 list1 seq 20 permit 192.168.0.0/16 ge 24
         - add routing prefix-list ipv4 list1 seq 30 deny any
         - add interface swp25 ip address 172.16.0.0/31
         - add bgp network 10.19.241.12/32
         - add bgp network 172.16.0.0/31
         - add bgp neighbor 172.16.0.1 remote-as 65001
         - add bgp neighbor SPINES peer-group
         - add bgp neighbor SPINES remote-as external
         - add bgp neighbor SPINES capability extended-nexthop
         - add bgp neighbor SPINES description Internal Fabric Network
         - add bgp neighbor swp29-30 interface peer-group SPINES
         - add bgp ipv4 unicast neighbor SPINES prefix-list list1 out
         - add bgp bestpath as-path multipath-relax

       commit: true

- hosts: bl2
  tasks:
   - name: Configure border leaf02
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.13/32
         - add bgp autonomous-system 65202
         - add routing prefix-list ipv4 list1 seq 10 permit 10.19.241.0/24 ge 32
         - add routing prefix-list ipv4 list1 seq 20 permit 192.168.0.0/16 ge 24
         - add routing prefix-list ipv4 list1 seq 30 deny any
         - add interface swp55 ip address 172.16.0.2/31
         - add bgp network 10.19.241.13/32
         - add bgp network 172.16.0.2/31
         - add bgp neighbor 172.16.0.3 remote-as 65001
         - add bgp neighbor SPINES peer-group
         - add bgp neighbor SPINES remote-as external
         - add bgp neighbor SPINES capability extended-nexthop
         - add bgp neighbor SPINES description Internal Fabric Network
         - add bgp neighbor swp53 interface peer-group SPINES
         - add bgp neighbor swp54 interface peer-group SPINES
         - add bgp ipv4 unicast neighbor SPINES prefix-list list1 out
         - add bgp bestpath as-path multipath-relax

       commit: true

- hosts: l3
  tasks:
   - name: Configure leaf03
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.14/32
         - add bgp autonomous-system 65203
         - add bgp network 10.19.241.14/32
         - add bgp neighbor SPINES peer-group
         - add bgp neighbor SPINES remote-as external
         - add bgp neighbor SPINES capability extended-nexthop
         - add bgp neighbor SPINES description Internal Fabric Network
         - add bgp neighbor swp53 interface peer-group SPINES
         - add bgp neighbor swp54 interface peer-group SPINES
         - add bgp bestpath as-path multipath-relax
         - add interface swp1-6,swp55-56
         - add vlan 160,161,70,60
         - add bond peerlink bond slaves swp55,swp56
         - add interface peerlink.4094 clag peer-ip linklocal
         - add interface peerlink.4094 clag backup-ip 192.168.200.9 vrf mgmt
         - add interface peerlink.4094 clag sys-mac 44:38:39:FF:01:56
         - add interface peerlink.4094 clag priority 100
         - add bridge bridge ports peerlink
         - add bridge stp treeprio 8192
         - add vlan 160 ip address 10.1.212.2/24
         - add vlan 160 ip address-virtual 00:00:5e:00:a0:01 10.1.212.1/24
         - add bgp ipv4 unicast network 10.1.212.0/24
         - add vlan 161 ip address 10.19.1.2/24
         - add vlan 161 ip address-virtual 00:00:5e:00:a1:01 10.19.1.1/24
         - add bgp ipv4 unicast network 10.19.1.0/24
         - add vlan 70 ip address 10.18.0.2/24
         - add vlan 70 ip address-virtual 00:00:5e:00:46:01 10.18.0.1/24
         - add bgp ipv4 unicast network 10.18.0.0/24
         - add vlan 60 ip address 10.18.10.2/24
         - add vlan 60 ip address-virtual 00:00:5e:00:3c:01 10.18.10.1/24
         - add bgp ipv4 unicast network 10.18.10.0/24
         - add interface swp1 post-up ip link set swp1 promisc on
         - add interface swp2 post-up ip link set swp2 promisc on
         - add interface swp3 post-up ip link set swp3 promisc on
         - add interface swp4 post-up ip link set swp4 promisc on
         - add interface swp5 post-up ip link set swp5 promisc on
         - add interface swp6 post-up ip link set swp6 promisc on
         - add interface swp55 post-up ip link set swp55 promisc on
         - add interface swp56 post-up ip link set swp56 promisc on
         - add bond bond01 bond slaves swp1
         - add bond bond01 clag id 1
         - add bond bond01 bridge trunk vlans 70,160-161
         - add bond bond02 bond slaves swp2
         - add bond bond02 clag id 2
         - add bond bond02 bridge trunk vlans 70,160-161
         - add bond bond03 bond slaves swp3
         - add bond bond03 clag id 3
         - add bond bond03 bridge trunk vlans 60
         - add bond bond04 bond slaves swp5
         - add bond bond04 clag id 4
         - add bond bond04 bridge trunk vlans 60

       commit: true

- hosts: l4
  tasks:
   - name: Configure leaf04
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.15/32
         - add bgp autonomous-system 65204
         - add bgp network 10.19.241.15/32
         - add bgp neighbor SPINES peer-group
         - add bgp neighbor SPINES remote-as external
         - add bgp neighbor SPINES capability extended-nexthop
         - add bgp neighbor SPINES description Internal Fabric Network
         - add bgp neighbor swp53 interface peer-group SPINES
         - add bgp neighbor swp54 interface peer-group SPINES
         - add bgp bestpath as-path multipath-relax
         - add interface swp1-6,swp55-56
         - add vlan 60,70,160,161
         - add bond peerlink bond slaves swp55,swp56
         - add interface peerlink.4094 clag peer-ip linklocal
         - add interface peerlink.4094 clag backup-ip 192.168.200.8 vrf mgmt
         - add interface peerlink.4094 clag sys-mac 44:38:39:FF:01:56
         - add bridge bridge ports peerlink
         - add bridge stp treeprio 8192
         - add vlan 160 ip address 10.1.212.3/24
         - add vlan 160 ip address-virtual 00:00:5e:00:a0:01 10.1.212.1/24
         - add bgp ipv4 unicast network 10.1.212.0/24
         - add vlan 161 ip address 10.19.1.3/24
         - add vlan 161 ip address-virtual 00:00:5e:00:a1:01 10.19.1.1/24
         - add bgp ipv4 unicast network 10.19.1.0/24
         - add vlan 70 ip address 10.18.0.3/24
         - add vlan 70 ip address-virtual 00:00:5e:00:46:01 10.18.0.1/24
         - add bgp ipv4 unicast network 10.18.0.0/24
         - add vlan 60 ip address 10.18.10.3/24
         - add vlan 60 ip address-virtual 00:00:5e:00:3c:01 10.18.10.1/24
         - add bgp ipv4 unicast network 10.18.10.0/24
         - add interface swp1 post-up ip link set swp1 promisc on
         - add interface swp2 post-up ip link set swp2 promisc on
         - add interface swp3 post-up ip link set swp3 promisc on
         - add interface swp4 post-up ip link set swp4 promisc on
         - add interface swp5 post-up ip link set swp5 promisc on
         - add interface swp6 post-up ip link set swp6 promisc on
         - add interface swp55 post-up ip link set swp55 promisc on
         - add interface swp56 post-up ip link set swp56 promisc on
         - add bond bond01 bond slaves swp1
         - add bond bond01 clag id 1
         - add bond bond01 bridge trunk vlans 70,160-161
         - add bond bond02 bond slaves swp2
         - add bond bond02 clag id 2
         - add bond bond02 bridge trunk vlans 70,160-161
         - add bond bond03 bond slaves swp3
         - add bond bond03 clag id 3
         - add bond bond03 bridge trunk vlans 60
         - add bond bond04 bond slaves swp5
         - add bond bond04 clag id 4
         - add bond bond04 bridge trunk vlans 60

       commit: true

- name: Configure Server LACP Interfaces
  hosts: servers
  become: yes
  gather_facts: yes
  tasks:

  - name: Copy Server LACP Interface Config
    copy:
      src: configurations/{{ansible_hostname}}/interfaces
      dest: /etc/network/interfaces
    register: reboot

  - name: reboot
    reboot:
      pre_reboot_delay: 60
